source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '7.0'

pod 'CrashlyticsFramework', '2.2.4'
pod 'FlurrySDK', '5.4.0'
pod 'Facebook-iOS-SDK', '3.19.0'
pod 'Bolts', '1.1.3'
pod 'FontAwesomeKit', '2.1.8'
pod 'HexColors', '2.2.1'
pod 'BlocksKit', '2.2.5'
pod 'SVProgressHUD', '1.0'
pod 'GeoJSONSerialization', '0.0.4'
pod 'AFNetworking', '1.3.4'
pod 'MHVideoPhotoGallery', '1.6.6'
pod 'UIColor-HTMLColors', '1.0.0'
pod 'SlackTextViewController', '1.2.7'
pod 'SVPullToRefresh', '0.4.1'
pod 'PDKTStickySectionHeadersCollectionViewLayout', '0.1'
